version: '3.9'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: land_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    restart: always
    ports:
      - "8080:8080"
    environment:
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_ADMIN_PASSWORD: geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver_data

  nestjs:
    build:
      context: ./nestjs
    container_name: nestjs
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: land_management
      JWT_SECRET: super-secret
      JWT_EXPIRES_IN: 1d
      RABBITMQ_URL: amqp://rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  postgres_data:
